### DISCUSSION TITLE
Translate Roam Garden into another language?

### DISCUSSION THREAD

**Discussion by sazovsky** [roam-garden/i#77] [Feature requests & Ideas]
I'm from Czech Republic and Roam believer. I will use Roam Reserach and Roam Garden for at least another 5 years. I will create RG in the Czech language.

Please, it is possible using CSS to translate min. "Orphan page" and "Referenced in"?

**Comment by Stvad** [comment]
Yes, this should be possible with "after replacement" trick. 

For example for the orphan content, you can do something like: 

```css
[id^=orphan] .block-body {
  display: none;
}

[id^=orphan]::after {
  content: "new content"
}
```
